#!/bin/bash
# Test script for xv6 file access logger
# This script demonstrates how to test the file access logging functionality

echo "=== xv6 File Access Logger Test Script ==="
echo ""
echo "To test the file access logger:"
echo ""
echo "1. Build xv6 with the modifications:"
echo "   make clean && make"
echo ""
echo "2. Run xv6 in QEMU:"
echo "   make qemu"
echo ""
echo "3. In the xv6 shell, run various commands to generate file access logs:"
echo "   $ cat README"
echo "   $ ls"
echo "   $ echo hello > test.txt"
echo "   $ cat test.txt"
echo "   $ grep hello test.txt"
echo ""
echo "4. View the file access logs:"
echo "   $ showlogs"
echo ""
echo "Expected output should show:"
echo "- Process ID (PID) of each command"
echo "- Filenames that were opened by each command"
echo "- Up to 100 log entries (circular buffer)"
echo ""
echo "The logger automatically captures all file opens via sys_open(),"
echo "so no manual instrumentation is needed in user programs."
